# Generated by Django 4.2.1 on 2023-06-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmb', '0003_alter_solicitud_confirmacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicicleta',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
