# Generated by Django 4.2.1 on 2023-06-26 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmb', '0004_bicicleta_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='solicitud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bmb.solicitud'),
        ),
    ]
