# Generated by Django 4.2.1 on 2023-06-26 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmb', '0005_alter_bicicleta_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='despacho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bmb.despacho'),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bmb.solicitud'),
        ),
    ]
