# Generated by Django 4.2.1 on 2023-06-26 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmb', '0007_alter_bicicleta_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiciReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('comentarios', models.TextField()),
                ('marca', models.CharField(max_length=20)),
                ('despacho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bmb.despacho')),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bmb.solicitud')),
            ],
        ),
    ]
