# Generated by Django 4.2.1 on 2023-06-26 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmb', '0008_bicireparacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bicireparacion',
            old_name='nombre',
            new_name='modelo',
        ),
    ]
